### ISSUE TITLE
Porting this functionality into ONNX-MXNet repo

### ISSUE THREAD

**Issue by lupesko** [NVIDIA/mxnet_to_onnx#1]
Hey Nvidia team,

Thanks for this work adding functionality to MXNet!
Not sure whether your know, but there is already a repo for MXNet/ONNX compatibility: [ONNX-MXNet](https://github.com/onnx/onnx-mxnet). It would be best for MXNet and ONNX users to have this functionality there, rather than having two separate repos.

I highly recommend to contribute a PR merging this functionality there.

Thanks!

**Comment by mkolod** [comment]
@lupesko Also, please note that the current project is serialized MxNet model-to-ONNX, and given our recent discovery of the instability of the serialized MxNet representation (frequent field renaming, say "param" to "params" and so on), maintaining the compatibility layer would be painful. We only disovered this while working on the implementation. However, since NNVM provides that compatibility layer even as serialized form breakages occur, it may make sense to provide an NNVM-to-ONNX exporter, the way ONNX-MxNet is based on importing from ONNX directly to NNVM (as far as I can tell). This will provide forward and backward compatibility. Since this is something that NVIDIA may contribute to anyway, that would probably be the version to be ultimately integrated into ONNX-MxNet. However, if you feel like integrating the current exporter into ONNX-MxNet as an intermediate solution is acceptable, please feel free to pick it up and integrate. Otherwise, stay tuned for NNVM-to-ONNX exporter for ONNX-MxNet.

**Comment by Roshrini** [comment]
@mkolod I agree that NNVM to ONNX makes more sense. This avoids users to have to checkpoint the model first after the training. Easier user experience would be to just export the model into onnx format after training with “MXNet module”. But this functionality(converting from model,params file) you have implemented is also useful for those who have pretrained models. I think We can provide both ways for users.

**Comment by mkolod** [comment]
@Roshrini This makes perfect sense. I'll be happy if both converters end up being useful! It's just that I won't have time to deal with merging the current one with ONNX-MxNet until the NNVM-ONNX one is done. If anyone at Amazon or the community would like to attempt that, please feel free to do so. Otherwise, I will come back to this task later on.
