### ISSUE TITLE
onnx_mxnet problem

### ISSUE THREAD

**Issue by cswwp** [NVIDIA/mxnet_to_onnx#4]
No local packages or working download links found for onnx_mxnet==0.4.0
error: Could not find suitable distribution for Requirement.parse('onnx_mxnet==0.4.0')

i have installed onnx_mxnet 0.4.0 with pip, but it still error when i execute install mxnet_to_onnx

**Comment by mkolod** [comment]
Hello, the latest commit should have fixed the problem. It no longer requires onnx_mxnet at all, since MxNet merged the ONNX importer into the main repository. However, more recent ONNX Python bindings required API updates in the converter. Things should work now if you do `python setup.py install`, followed by `python setup.py test`. Note the changes in `requirements.txt` - MxNet >= 1.2 is now required.
